services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HauerHeinrich\HhVideoExtender\:
    resource: '../Classes/*'

  HauerHeinrich\HhVideoExtender\Rendering\:
    resource: '../Classes/Rendering/*'
    public: true
